# --------------------------------------------------------------
# WARNING: This file is managed by centralized sync management system.
# Do not edit this file directly, your changes will be overwritten.
# See https://github.com/orange-cloudavenue/workflows for more information.
# --------------------------------------------------------------
plugin "terraform" {
  enabled = true
  preset  = "recommended"
}