# Terraform Provider testing workflow.
name: Lint

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
    pull_request:
      paths:
        - '**.tf'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: cache tflint
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('.tflint.hcl') }}
    - name: setup tflint
      uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
    - name: tflint init
      run: tflint --init
    - name: tflint validate
      run: tflint -f compact --module